SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error { border-color: red; background-color: #fee ; }
    </style>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
</head>
<body class="m-1 p-1">
    <div class="bg-info p-2 row">
        <div class="col">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2">
            <a class="btn btn-sm btn-primary"
               asp-action="Logout" asp-controller="Account">Log Out</a>
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!-- Layout das von allen Views geteilt wird -->
  <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet"
              asp-href-include="/lib/bootstrap/dist/css/*.min.css"
              asp-href-exclude="/lib/bootstrap/dist/css/bootstrap-grid.min.css" />
        <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css" />
        <title>SportsStore</title>
    </head>
    <body>
        <!-- navbar navbar navbar-dark bg-dark -->
        <div class="" role="navigation">
            <div class="navbar navbar-dark bg-dark">
                <div class="col-md-6 navbar-brand">
                    <a style="color:white" href="#">Sports Store</a>
                </div>
                <div class="col-md-3 text-right">
                    @await Component.InvokeAsync("CartSummary")
                </div>
            </div>
        </div>
        <div class="row m-1 p-1">
            <div id="categories" class="col-3">
                @await Component.InvokeAsync("NavigationMenu")
            </div>
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
    </body>
    </html>